name: Build
on: [push, pull_request]
env:
  DOTNET_NOLOGO: true # remove after: https://github.com/actions/virtual-environments/pull/957

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Build Reason
      run: "echo ref: ${{github.ref}} event: ${{github.event_name}}"
    - name: Build Version
      run: |
        dotnet tool install --global minver-cli --version 2.3.0
        version=$(minver --tag-prefix v)
        echo "::set-env name=MINVERVERSIONOVERRIDE::$version"
    - name: Build
      run: dotnet build --configuration Release
    - name: Start Services
      run: docker-compose up -d
    - name: Run Tests
      run: dotnet test --configuration Release --no-build
    - name: Package
      if: github.event_name != 'pull_request'
      run: dotnet pack --configuration Release --no-build
    - name: Publish CI Packages
      if: github.event_name != 'pull_request'
      run: |
        for package in $(find -name "*.nupkg" | grep "minver" -v); do
          echo "${0##*/}": Pushing $package...
          
          # GPR - workaround for GPR not working with API key
          echo "Pushing $package to GPR..."
          STATUSCODE=$(curl -sX --write-out "%{http_code}" PUT -u "foundatiofx:${{ secrets.GITHUB_TOKEN }}" -F package=@$package https://nuget.pkg.github.com/foundatiofx/)
          if test $STATUSCODE -ne 200; then
              echo "Failed to push"
          else
              echo "Your package was pushed."
          fi

          # feedz (remove once GPR supports anonymous access)
          dotnet nuget push $package --source https://f.feedz.io/foundatio/foundatio/nuget --api-key ${{ secrets.FEEDZ_KEY }} --skip-duplicate
        done
    - name: Publish Release Packages
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        for package in $(find -name "*.nupkg" | grep "minver" -v); do
          echo "${0##*/}": Pushing $package...
          dotnet nuget push $package --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_KEY }} --skip-duplicate
        done

